### ISSUE TITLE
How to download in excel/csv the FDA drug enforcements from 2004 to present?

### ISSUE THREAD

**Issue by Arusik** [FDA/open.fda.gov#133]
How can I download drug enforcements data in Excel/CSV format from 2004 to present? The JSTON file available in here  - https://open.fda.gov/drug/enforcement/ - contains only 2012-2017 records. However Open FDA says to keep records starting from 2004.

**Comment by beardedfinch** [comment]
Going through old issues. For posterity's sake: [https://open.fda.gov/apis/drug/event/download/](https://open.fda.gov/apis/drug/event/download/)
