### ISSUE TITLE
What is the difference between the FDA inspection observations and the inspection citations reports? 

### ISSUE THREAD

**Issue by FDAcurious** [FDA/open.fda.gov#143]

**Comment by melissawalker** [comment]
Inspectors note observations (undesirable conditions) that are connected to specific regulation citations.  For example, an inspection conducted at Oscar, Inc in August 2016 yielded a 483 (Inspectional Observations) with three noted observations.  Observation 3: "Procedures for training and identifying training needs have not been adequately established."  This observation is relevant to 21 CFR 820.25(b).

**Comment by beardedfinch** [comment]
Closing as this is beyond the scope of our work (and very old).
