### ISSUE TITLE
Is FDA/OpenFDA currently maintained?

### ISSUE THREAD

**Issue by beckyconning** [FDA/open.fda.gov#164]
Hi! I opened an issue (https://github.com/FDA/openfda/issues/103) and pull request (https://github.com/FDA/openfda/pull/104) last week and haven't yet received any response. I'm trying to work out if I will receive a response or if I will need to run my own OpenFDA service.

My colleagues claim that it is not maintained and that I should not expect a response.

`FDA/open.fda.gov` seems more active than `FDA/openfda` so I thought I would ask here.

Either way is fine, just trying to understand next steps.

Thank you.

**Comment by beardedfinch** [comment]
Hi Becky, openFDA is indeed being maintained, sorry it took us a bit of time to respond to your previous issue. Please refer to Denis' comment there. Thanks!

**Comment by beckyconning** [comment]
No worries! Thanks for the reply and clarification @beardedfinch.
