### ISSUE TITLE
Hasn't been updated since Dec 2019

### ISSUE THREAD

**Issue by sdcharle** [FDA/open.fda.gov#173]
Is this project still alive? Looks like data hasn't been updated since December 2019. It's a shame, it was a very good resource for data pipelines.

**Comment by beardedfinch** [comment]
Hi @sdcharle, I'm Jack with the openFDA Team. The temporary suspension of updates to the openFDA datasets has ended. We're in the process of updating all datasets. Please stay tuned in to the [API Status page](https://open.fda.gov/about/status/) for update details. Thank you!
