### ISSUE TITLE
Search/count on adverse event records where a specified active substance name is suspect?

### ISSUE THREAD

**Issue by gavinhardin** [FDA/open.fda.gov#204]
Hello,

Thanks for providing this API. Is it possible to perform a search on the adverse events endpoint to filter by records with a given `patient.drug.activesubstance.activesubstancename` AND with that drug's `drugcharacterization` being a certain value? 

I am interested in retrieving a count on records where a specified drug is listed as suspect. The closest query I can come up with is https://api.fda.gov/drug/event.json?search=patient.drug.activesubstance.activesubstancename:tretinoin+AND+patient.drug.drugcharacterization:1&limit=100, but this doesn't ensure that the given active substance has the specified drug characterization, only that *a drug* in the record is listed as suspect.

If this is not currently possible, it would be a very useful feature to add.

**Comment by dkrylovsb** [comment]
Unfortunately, this is not currently possible in openFDA (technical details [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html); openFDA does not utilize `nested` fields). We will look into implementing this in future releases, however.

**Comment by gavinhardin** [comment]
> Unfortunately, this is not currently possible in openFDA (technical details [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html); openFDA does not utilize `nested` fields). We will look into implementing this in future releases, however.

Understood. Thanks for the prompt reply!
