### ISSUE TITLE
Typo: 'Ractions'

### ISSUE THREAD

**Issue by JasonTam** [FDA/open.fda.gov#82]
There's a typo on [this page](https://github.com/FDA/open.fda.gov/blob/8b3910eda0dc7207495a98843a7816fa1e54ca39/drug/event/reference/index.md)

'Ractions' should be 'Reactions' ?

**Comment by mattmo** [comment]
Thanks for pointing this out. We'll take care of this soon. Will update the bug when we do.

**Comment by mattmo** [comment]
This is now fixed and pushed
